"""added more cols. Users

Revision ID: 004ba230b141
Revises: 69704835827b
Create Date: 2024-02-07 14:34:04.336972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004ba230b141'
down_revision = '69704835827b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_password'), ['password'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_password'))
        batch_op.drop_index(batch_op.f('ix_users_gender'))
        batch_op.drop_column('gender')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
