"""added new DB

Revision ID: 69704835827b
Revises: 
Create Date: 2024-02-07 14:14:03.443376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69704835827b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_category', sa.String(length=64), nullable=True),
    sa.Column('meal_area', sa.String(length=64), nullable=True),
    sa.Column('date_input', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_date_input'), ['date_input'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_meal_area'), ['meal_area'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_meal_category'), ['meal_category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_meal_category'))
        batch_op.drop_index(batch_op.f('ix_meal_meal_area'))
        batch_op.drop_index(batch_op.f('ix_meal_id'))
        batch_op.drop_index(batch_op.f('ix_meal_date_input'))

    op.drop_table('meal')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_last_name'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_first_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
